### ISSUE TITLE
Does not support image upload, like simple image upload adapter.

### ISSUE THREAD

**Issue by yoyo837** [eMAGTechLabs/ckeditor5-file-upload#5]
https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/simple-upload-adapter.html

**Comment by yoyo837** [comment]
I solved it.

**Comment by goapunk** [comment]
@yoyo837 how did you solve it ? the normal image upload doesn't seem to work anymore

**Comment by yoyo837** [comment]
> @yoyo837 how did you solve it ? the normal image upload doesn't seem to work anymore

I made some changes based on this repo. If you need, I can share some code snippets with you.

**Comment by goapunk** [comment]
@yoyo837 thanks for the quick reply :) I think I just got it working with the `simpleUploadAdapter` included in the ckeditor5. I don't really understand why the custom one in this repo is required.

**Comment by yoyo837** [comment]
> @yoyo837 thanks for the quick reply :) I think I just got it working with the `simpleUploadAdapter` included in the ckeditor5. I don't really understand why the custom one in this repo is required.

Because I hope it supports the upload of other files besides images.

<img width="1123" alt="image" src="https://github.com/eMAGTechLabs/ckeditor5-file-upload/assets/6134547/59d659bf-40d3-471c-807d-bdf6468f5f3e">
